services:
  telegram_bot:
    build:
      context: .
      dockerfile: ./telegram.Dockerfile
    restart: always
    environment:
      TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
    volumes:
      - ./logs:/src/logs
  discord_bot:
    build:
      context: .
      dockerfile: ./discord.Dockerfile
    restart: always
    environment:
      DISCORD_BOT_API_KEY: ${DISCORD_BOT_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./logs:/src/logs